version: '2.1'
services:

  fhir-baseos:
    build:
        context: .
        dockerfile: Dockerfile-fhirbaseos
    image: fhir-baseos:latest
    hostname: fhir-baseos

  fhir-basic:
    build:
        context: .
        dockerfile: Dockerfile-fhirbasic
    image: fhir-basic:${FHIR_DOCKER_TAG}
    hostname: fhir-basic
    ports:
      - 9080:9080
      - 9443:9443

  fhir-test:
    build:
        context: .
        dockerfile: Dockerfile-fhirtest
    image: fhir-test:${FHIR_DOCKER_TAG}
    hostname: fhir-test
    healthcheck:
      interval: 20s
      timeout: 10s
      retries: 60
      test: curl -v -f -k -u 'fhiruser:fhiruser' https://localhost:9443/fhir-server/api/v1/metadata
    ports:
      - 9080:9080
      - 9443:9443

  fhir-proxy:
    build:
        context: .
        dockerfile: Dockerfile-fhirbaseos
    image: fhir-proxy:${FHIR_DOCKER_TAG}
    depends_on:
      fhir-test:
        condition: service_healthy
    command: sleep 1
