version: '2.1'
services:

  fhir-baseos:
    build:
        context: .
        dockerfile: Dockerfile-fhirbaseos
    image: fhir-baseos:latest
    hostname: fhir-baseos

  fhir-basic:
    build:
        context: .
        dockerfile: Dockerfile-fhirbasic
    image: fhir-basic
    hostname: fhir-basic
    ports:
      - 9080:9080
      - 9443:9443

  fhir-test:
    build:
        context: .
        dockerfile: Dockerfile-fhirtest
    image: fhir-test
    hostname: fhir-test
    healthcheck:
      interval: 30s
      timeout: 30s
      retries: 80
      test: curl -v -f -k -u 'fhiruser:fhiruser' https://localhost:9443/fhir-server/api/v4/metadata
    ports:
      - 9080:9080
      - 9443:9443
    command: |
      bash -c "
      su - fhir -c '/opt/ibm/fhir-server/wlp/bin/server run fhir-server';
      tail -F -n +1 /opt/ibm/fhir-server/wlp/usr/servers/fhir-server/logs/messages.log
      "

  fhir-proxy:
    build:
        context: .
        dockerfile: Dockerfile-fhirbaseos
    image: fhir-proxy
    depends_on:
      fhir-test:
        condition: service_healthy
    command: sleep 1
