name: Build and Release

on:
  push:
    tags:
      - '*.*'
    paths-ignore:
    - 'docs/**'
    - '.github/workflows/site.yml'
    - '.github/workflows/javadocs.yml'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk11' ]
      fail-fast: false
    steps:
    - name: Grab the Main Branch
      uses: actions/checkout@v2.3.3
      with:
        ref: refs/heads/main
        fetch-depth: 1
    - name: Setup OpenJDK
      uses: joschi/setup-jdk@v2.3.0
      with:
        java-version: ${{ matrix.java }}
    - name: Prep
      env:
        BASE: origin/${{ github['base_ref'] }}
        GITHUB_TOKEN: ${{ secrets.DOCS_SITE_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        . build/release/bin/global.sh
        bash build/release/00_prep.sh
        bash build/release/10_build.sh
        bash build/release/20_test.sh
        bash build/release/30_stage.sh
        bash build/release/40_release.sh
        bash build/release/50_drop.sh
    - name: Gather artifacts and materials
      if: always()
      run: |
        bash build/release/60_gather.sh
    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v2.2.3
      with:
        name: release-${{ github.tag }}
        path: |
          build/release/workarea/release_files
        if-no-files-found: ignore