name: Build and Release

on:
  push:
    tags:
      - '*.*'
    paths-ignore:
    - 'docs/**'
    - '.github/workflows/site.yml'
    - '.github/workflows/javadocs.yml'

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 'openjdk11' ]
      fail-fast: false
    steps:
    - name: Grab the Main Branch
      uses: actions/checkout@v2.3.3
      with:
        ref: refs/heads/main
        fetch-depth: 1
    - name: Setup OpenJDK
      uses: joschi/setup-jdk@v2.3.0
      with:
        java-version: ${{ matrix.java }}
    - name: Prep
      env:
        BASE: origin/${{ github['base_ref'] }}
        GITHUB_TOKEN: ${{ secrets.DOCS_SITE_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        bash build/release/prep.sh
    - name: Build
      run: |
        bash build/release/build.sh
    - name: Package Artifacts
      run: |
        bash build/release/package.sh
    - name: Release
      run: |
        bash build/release/release.sh
    - name: Gather error logs
      if: failure()
      run: |
        bash build/release/diagnostics.sh
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: release-tag-${{ matrix.java }}
        path: release-test-coverage-and-logs.tgz
    - name: Upload Artifacts - Distribution
      if: success()
      uses: actions/upload-artifact@v2.2.0
      with:
        name: release-${{ github.tag }}
        path: |
          build/.cache/
        if-no-files-found: ignore
